name: DevOps Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      # ✅ Fix docker build error
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # ✅ Security scan
      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs


      # ✅ Login
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # ✅ Build
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio .


      # ✅ Push
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/portfolio


      # ✅ Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4


      - name: Upload Site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .


      - name: Deploy Site
        uses: actions/deploy-pages@v4